const types = {
  ADD_GOAL: 'ADD_GOAL',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SEARCH_GOAL: 'SEARCH_GOAL',
  DONE: 'DONE',
  REMOVE: 'REMOVE',
  TITLE_UPDATE: 'TITLE_UPDATE',
  DESCRIPTION_UPDATE: 'DESCRIPTION_UPDATE',
};

export default types;
