const types = {
  ADD_GOAL: 'ADD_GOAL',
  TOGGLE_ADD_GOAL_MODAL: 'TOGGLE_ADD_GOAL_MODAL',
  TOGGLE_PREVIEW_GOAL_MODAL: 'TOGGLE_PREVIEW_GOAL_MODAL',
  SEARCH_GOAL: 'SEARCH_GOAL',
  DONE: 'DONE',
  REMOVE: 'REMOVE',
  TITLE_UPDATE: 'TITLE_UPDATE',
  DESCRIPTION_UPDATE: 'DESCRIPTION_UPDATE',
};

export default types;
